name: nightly-build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *" # Daily “At 00:00”

jobs:
  build:
    if: ${{ github.repository_owner == 'kgoebber' }}
    uses: ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml@main
    with:
      environment_name: metpy_book
      environment_file: environment.yml

  link-check:
    if: ${{ github.repository_owner == 'kgoebber' }}
    uses: ProjectPythia/cookbook-actions/.github/workflows/link-checker.yaml@main
